export enum genreClasses {
  'Action' = 'action',
  'Adventure' = 'adventure',
  'Animation' = 'animation',
  'Comedy' = 'comedy',
  'Crime' = 'crime',
  'Documentary' = 'documentary',
  'Drama' = 'drama',
  'Family' = 'family',
  'Fantasy' = 'fantasy',
  'History' = 'history',
  'Horror' = 'horror',
  'Music' = 'music',
  'Mystery' = 'mystery',
  'Romance' = 'romance',
  'Science Fiction' = 'sciencefiction',
  'TV Movie' = 'tv',
  'Thriller' = 'thriller',
  'War' = 'war',
  'Western' = 'western',
}
